/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.JPanel;

/**
 *
 * @author Carlos Fabricio
 */
public class DashboardProducts extends javax.swing.JFrame {

    /**
     * Creates new form DashboardProductos
     */
    public DashboardProducts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBackground = new javax.swing.JPanel();
        panMenu = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnCategoriesPan = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnProductsPan = new javax.swing.JButton();
        btnCategoriesPan1 = new javax.swing.JButton();
        btnCategoriesPan2 = new javax.swing.JButton();
        panContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(900, 400));

        panMenu.setBackground(new java.awt.Color(255, 102, 102));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("BodeBandidos");

        btnCategoriesPan.setBackground(new java.awt.Color(255, 102, 102));
        btnCategoriesPan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCategoriesPan.setForeground(new java.awt.Color(255, 255, 255));
        btnCategoriesPan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user-ico.png"))); // NOI18N
        btnCategoriesPan.setText("Customers");
        btnCategoriesPan.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 10, 20, 20, new java.awt.Color(0, 0, 0)));
        btnCategoriesPan.setBorderPainted(false);
        btnCategoriesPan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCategoriesPan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCategoriesPan.setIconTextGap(10);
        btnCategoriesPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriesPanActionPerformed(evt);
            }
        });

        btnProductsPan.setBackground(new java.awt.Color(255, 102, 102));
        btnProductsPan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnProductsPan.setForeground(new java.awt.Color(255, 255, 255));
        btnProductsPan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-product-30.png"))); // NOI18N
        btnProductsPan.setText("Products");
        btnProductsPan.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnProductsPan.setBorderPainted(false);
        btnProductsPan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProductsPan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnProductsPan.setIconTextGap(10);
        btnProductsPan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductsPanActionPerformed(evt);
            }
        });

        btnCategoriesPan1.setBackground(new java.awt.Color(255, 102, 102));
        btnCategoriesPan1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCategoriesPan1.setForeground(new java.awt.Color(255, 255, 255));
        btnCategoriesPan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/order-ico.png"))); // NOI18N
        btnCategoriesPan1.setText("Orders");
        btnCategoriesPan1.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 10, 20, 20, new java.awt.Color(0, 0, 0)));
        btnCategoriesPan1.setBorderPainted(false);
        btnCategoriesPan1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCategoriesPan1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCategoriesPan1.setIconTextGap(10);
        btnCategoriesPan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriesPan1ActionPerformed(evt);
            }
        });

        btnCategoriesPan2.setBackground(new java.awt.Color(255, 102, 102));
        btnCategoriesPan2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCategoriesPan2.setForeground(new java.awt.Color(255, 255, 255));
        btnCategoriesPan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/categoryico.png"))); // NOI18N
        btnCategoriesPan2.setText("Categories");
        btnCategoriesPan2.setBorder(javax.swing.BorderFactory.createMatteBorder(20, 10, 20, 20, new java.awt.Color(0, 0, 0)));
        btnCategoriesPan2.setBorderPainted(false);
        btnCategoriesPan2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCategoriesPan2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCategoriesPan2.setIconTextGap(10);
        btnCategoriesPan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriesPan2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panMenuLayout = new javax.swing.GroupLayout(panMenu);
        panMenu.setLayout(panMenuLayout);
        panMenuLayout.setHorizontalGroup(
            panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuLayout.createSequentialGroup()
                .addGroup(panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panMenuLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnProductsPan, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
            .addComponent(btnCategoriesPan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCategoriesPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCategoriesPan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panMenuLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panMenuLayout.setVerticalGroup(
            panMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panMenuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitle)
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btnProductsPan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCategoriesPan2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(btnCategoriesPan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCategoriesPan1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panContentLayout = new javax.swing.GroupLayout(panContent);
        panContent.setLayout(panContentLayout);
        panContentLayout.setHorizontalGroup(
            panContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        panContentLayout.setVerticalGroup(
            panContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panBackgroundLayout = new javax.swing.GroupLayout(panBackground);
        panBackground.setLayout(panBackgroundLayout);
        panBackgroundLayout.setHorizontalGroup(
            panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBackgroundLayout.createSequentialGroup()
                .addComponent(panMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1)
                .addComponent(panContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panBackgroundLayout.setVerticalGroup(
            panBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCategoriesPanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriesPanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCategoriesPanActionPerformed

    private void btnCategoriesPan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriesPan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCategoriesPan1ActionPerformed

    private void btnCategoriesPan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriesPan2ActionPerformed
        //ShowJPanel(new CategoriesView());
    }//GEN-LAST:event_btnCategoriesPan2ActionPerformed

    private void btnProductsPanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductsPanActionPerformed
        //ShowJPanel(new ProductView());
    }//GEN-LAST:event_btnProductsPanActionPerformed

    public static void ShowJPanel(JPanel p) {
        p.setSize(750, 430);
        p.setLocation(0,0);
        
        //panContent.removeAll();
        //panContent.add(p, BorderLayout.CENTER);
        //panContent.revalidate();
        //panContent.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatLightLaf.setup();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCategoriesPan;
    private javax.swing.JButton btnCategoriesPan1;
    private javax.swing.JButton btnCategoriesPan2;
    private javax.swing.JButton btnProductsPan;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panBackground;
    private javax.swing.JPanel panContent;
    private javax.swing.JPanel panMenu;
    // End of variables declaration//GEN-END:variables
}
